#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""
Compute plugin load addresses and base stub symbol addresses from a built
base stub ELF.  Writes a CMake-includable file with the results.

Usage:
    compute_plugin_addrs.py <base_stub_elf> <output_cmake_file>
"""
import sys

try:
    from elftools.elf.elffile import ELFFile
    from elftools.elf.sections import SymbolTableSection
except ImportError:
    raise SystemExit(
        "pyelftools not found. Install with: pip install pyelftools"
    )


def get_symbol_addr(elf, name):
    """Return the VMA of symbol *name*, or None if not found."""
    for section in elf.iter_sections():
        if not isinstance(section, SymbolTableSection):
            continue
        for sym in section.iter_symbols():
            if sym.name == name and sym['st_value'] != 0:
                return sym['st_value']
    return None


def align_up(value, alignment):
    return (value + alignment - 1) & ~(alignment - 1)


def main():
    if len(sys.argv) != 3:
        sys.exit(f"Usage: {sys.argv[0]} <base_stub_elf> <output.cmake>")

    elf_path, cmake_out = sys.argv[1], sys.argv[2]

    with open(elf_path, "rb") as f:
        elf = ELFFile(f)

        text_sec = elf.get_section_by_name(".text")
        data_sec = elf.get_section_by_name(".data")

        if text_sec is None:
            sys.exit("ERROR: .text section not found in base stub ELF")
        if data_sec is None:
            sys.exit("ERROR: .data section not found in base stub ELF")

        text_end = text_sec["sh_addr"] + text_sec["sh_size"]
        data_end = data_sec["sh_addr"] + data_sec["sh_size"]

        plugin_text_addr = align_up(text_end, 16)
        plugin_bss_addr  = align_up(data_end, 4)

        # Symbols forwarded to the plugin via PROVIDE in the linker script
        slip_syms = [
            "slip_send_frame",
            "slip_recv_reset",
            "slip_is_frame_complete",
            "slip_get_frame_data",
        ]

        sym_addrs = {}
        for name in slip_syms:
            addr = get_symbol_addr(elf, name)
            if addr is None:
                sys.exit(f"ERROR: symbol '{name}' not found in base stub ELF")
            sym_addrs[name] = addr

    lines = [
        f"set(NAND_PLUGIN_TEXT_ADDR 0x{plugin_text_addr:08X})",
        f"set(NAND_PLUGIN_BSS_ADDR  0x{plugin_bss_addr:08X})",
        f"set(SLIP_SEND_FRAME_ADDR         0x{sym_addrs['slip_send_frame']:08X})",
        f"set(SLIP_RECV_RESET_ADDR         0x{sym_addrs['slip_recv_reset']:08X})",
        f"set(SLIP_IS_FRAME_COMPLETE_ADDR  0x{sym_addrs['slip_is_frame_complete']:08X})",
        f"set(SLIP_GET_FRAME_DATA_ADDR     0x{sym_addrs['slip_get_frame_data']:08X})",
    ]

    with open(cmake_out, "w") as out:
        out.write("# Auto-generated by compute_plugin_addrs.py — do not edit\n")
        for line in lines:
            out.write(line + "\n")

    print(f"Plugin addresses written to {cmake_out}")
    for line in lines:
        print(f"  {line}")


if __name__ == "__main__":
    main()
