#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""
Compute a plugin's load addresses from the base stub ELF and emit a linker
script fragment defining PLUGIN_TEXT_ADDR and PLUGIN_BSS_ADDR.

A plugin is loaded immediately after the base stub.  Multiple plugins stack:
pass each preceding plugin's ELF via --after, in load order, so this plugin is
placed after them.

    # First plugin: right after the base stub
    compute_plugin_addrs.py base.elf nand_plugin_addrs.ld

    # Second plugin: stacked after the first
    compute_plugin_addrs.py base.elf spi_ram_plugin_addrs.ld --after nand_plugin.elf

The generated fragment is pulled in by the plugin's linker script via -T and
supplies the MEMORY origins, replacing the old configure-time -Wl,--defsym.
"""

import argparse
import sys

try:
    from elftools.elf.elffile import ELFFile
except ImportError:
    raise SystemExit('pyelftools not found. Install with: pip install pyelftools')


def align_up(value, alignment):
    return (value + alignment - 1) & ~(alignment - 1)


def _section_end(elf, name, path):
    sec = elf.get_section_by_name(name)
    if sec is None:
        sys.exit(f'ERROR: {name} section not found in base stub ELF {path}')
    return sec['sh_addr'] + sec['sh_size']


def _section_size(elf, name):
    sec = elf.get_section_by_name(name)
    return sec['sh_size'] if sec is not None else 0


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('base_stub_elf', help='Path to the base stub ELF file')
    parser.add_argument('output_ld', help='Path to the linker fragment to write')
    parser.add_argument(
        '--after',
        action='append',
        default=[],
        metavar='PLUGIN_ELF',
        help='ELF of a plugin loaded before this one; repeat in load order to stack.',
    )
    args = parser.parse_args()

    with open(args.base_stub_elf, 'rb') as f:
        elf = ELFFile(f)
        text_end = _section_end(elf, '.text', args.base_stub_elf)
        data_end = _section_end(elf, '.data', args.base_stub_elf)
        bss_end = _section_end(elf, '.bss', args.base_stub_elf)

    # First plugin slot starts immediately after the base stub.  Place plugin
    # BSS after both .data and .bss to avoid overlap.
    text_addr = align_up(text_end, 16)
    bss_addr = align_up(max(data_end, bss_end), 4)

    # Stack past each preceding plugin, in load order.
    for plugin_elf in args.after:
        try:
            with open(plugin_elf, 'rb') as pf:
                p_elf = ELFFile(pf)
                p_text_size = _section_size(p_elf, '.text')
                p_bss_size = _section_size(p_elf, '.bss')
        except FileNotFoundError:
            sys.exit(f"ERROR: preceding plugin ELF not found: '{plugin_elf}'")
        text_addr = align_up(text_addr + p_text_size, 16)
        bss_addr = align_up(bss_addr + p_bss_size, 4)

    with open(args.output_ld, 'w') as out:
        out.write('/* Auto-generated by compute_plugin_addrs.py — do not edit */\n')
        out.write(f'PLUGIN_TEXT_ADDR = 0x{text_addr:08X};\n')
        out.write(f'PLUGIN_BSS_ADDR  = 0x{bss_addr:08X};\n')

    print(f'Plugin load addresses written to {args.output_ld}')
    print(f'  PLUGIN_TEXT_ADDR = 0x{text_addr:08X}')
    print(f'  PLUGIN_BSS_ADDR  = 0x{bss_addr:08X}')


if __name__ == '__main__':
    main()
